/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.cafe.ui;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import javax.swing.Timer;
import javax.swing.UIManager;
import poly.cafe.util.Constrants;
import poly.cafe.util.XIcon;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Font;
import java.awt.Point;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.ToolTipManager;
import poly.cafe.util.HoverUtil;

/**
 *
 * @author Phu Pham
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private final int COLLAPSED_WIDTH = 40;
    private final int EXPANDED_WIDTH = 200;
    private final int ANIMATION_DELAY = 7; // ms
    private final int STEP_SIZE = 20; // mỗi lần tăng/giảm bao nhiêu pixel
    private Timer expandTimer;
    private Timer collapseTimer;
    public Boolean navOpen = false;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        ToolTipManager.sharedInstance().setInitialDelay(0);

        // Tùy chỉnh font, màu tooltip
        UIManager.put("ToolTip.font", new Font("Segoe UI", Font.PLAIN, 14));
        UIManager.put("ToolTip.background", Color.BLACK);
        UIManager.put("ToolTip.foreground", Color.WHITE);
        UIManager.put("ToolTip.border", BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        this.initPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNav = new javax.swing.JPanel();
        lblSideBar = new javax.swing.JLabel(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/sidebar.svg", 24, 24));
        space2 = new javax.swing.JPanel();
        lblNguoiThue = new javax.swing.JLabel(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/user.svg", 24, 24));
        space3 = new javax.swing.JPanel();
        lblDoanhThu = new javax.swing.JLabel(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/money.svg", 24, 24));
        space1 = new javax.swing.JPanel();
        lblHopDong = new javax.swing.JLabel(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/contract.svg", 24, 24));
        space4 = new javax.swing.JPanel();
        lblChiNhanh = new javax.swing.JLabel(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/branch.svg", 24, 24));
        space5 = new javax.swing.JPanel();
        lblDienNuoc3 = new javax.swing.JLabel(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/water.svg", 24, 24));
        space6 = new javax.swing.JPanel();
        lblPhong = new javax.swing.JLabel(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/room.svg", 24, 24));
        space7 = new javax.swing.JPanel();
        lblHoaDon = new javax.swing.JLabel(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/bill.svg", 24, 24));
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlNav.setBackground(new java.awt.Color(249, 249, 249));
        pnlNav.setForeground(new java.awt.Color(255, 255, 255));
        pnlNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNavMouseExited(evt);
            }
        });
        pnlNav.setLayout(new javax.swing.BoxLayout(pnlNav, javax.swing.BoxLayout.Y_AXIS));

        lblSideBar.setText("item 1");
        lblSideBar.setToolTipText("");
        lblSideBar.setIconTextGap(10);
        lblSideBar.setName(""); // NOI18N
        lblSideBar.setOpaque(true);
        lblSideBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSideBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSideBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSideBarMouseExited(evt);
            }
        });
        pnlNav.add(lblSideBar);

        space2.setBackground(new java.awt.Color(249, 249, 249));
        space2.setForeground(new java.awt.Color(255, 255, 255));
        space2.setMaximumSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout space2Layout = new javax.swing.GroupLayout(space2);
        space2.setLayout(space2Layout);
        space2Layout.setHorizontalGroup(
            space2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        space2Layout.setVerticalGroup(
            space2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        pnlNav.add(space2);

        lblNguoiThue.setText("item 2");
        lblNguoiThue.setToolTipText("");
        lblNguoiThue.setIconTextGap(10);
        lblNguoiThue.setOpaque(true);
        lblNguoiThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNguoiThueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNguoiThueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNguoiThueMouseExited(evt);
            }
        });
        pnlNav.add(lblNguoiThue);

        space3.setBackground(new java.awt.Color(249, 249, 249));
        space3.setForeground(new java.awt.Color(255, 255, 255));
        space3.setMaximumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout space3Layout = new javax.swing.GroupLayout(space3);
        space3.setLayout(space3Layout);
        space3Layout.setHorizontalGroup(
            space3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        space3Layout.setVerticalGroup(
            space3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlNav.add(space3);

        lblDoanhThu.setForeground(new java.awt.Color(51, 51, 51));
        lblDoanhThu.setText("item 3");
        lblDoanhThu.setToolTipText("");
        lblDoanhThu.setIconTextGap(10);
        lblDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoanhThuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDoanhThuMouseEntered(evt);
            }
        });
        pnlNav.add(lblDoanhThu);

        space1.setBackground(new java.awt.Color(249, 249, 249));
        space1.setForeground(new java.awt.Color(255, 255, 255));
        space1.setMaximumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout space1Layout = new javax.swing.GroupLayout(space1);
        space1.setLayout(space1Layout);
        space1Layout.setHorizontalGroup(
            space1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        space1Layout.setVerticalGroup(
            space1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlNav.add(space1);

        lblHopDong.setForeground(new java.awt.Color(51, 51, 51));
        lblHopDong.setText("item 3");
        lblHopDong.setToolTipText("");
        lblHopDong.setIconTextGap(10);
        lblHopDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHopDongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHopDongMouseEntered(evt);
            }
        });
        pnlNav.add(lblHopDong);

        space4.setBackground(new java.awt.Color(249, 249, 249));
        space4.setForeground(new java.awt.Color(255, 255, 255));
        space4.setMaximumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout space4Layout = new javax.swing.GroupLayout(space4);
        space4.setLayout(space4Layout);
        space4Layout.setHorizontalGroup(
            space4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        space4Layout.setVerticalGroup(
            space4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlNav.add(space4);

        lblChiNhanh.setForeground(new java.awt.Color(51, 51, 51));
        lblChiNhanh.setText("item 3");
        lblChiNhanh.setToolTipText("");
        lblChiNhanh.setIconTextGap(10);
        lblChiNhanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChiNhanhMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblChiNhanhMouseEntered(evt);
            }
        });
        pnlNav.add(lblChiNhanh);

        space5.setBackground(new java.awt.Color(249, 249, 249));
        space5.setForeground(new java.awt.Color(255, 255, 255));
        space5.setMaximumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout space5Layout = new javax.swing.GroupLayout(space5);
        space5.setLayout(space5Layout);
        space5Layout.setHorizontalGroup(
            space5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        space5Layout.setVerticalGroup(
            space5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlNav.add(space5);

        lblDienNuoc3.setForeground(new java.awt.Color(51, 51, 51));
        lblDienNuoc3.setText("item 3");
        lblDienNuoc3.setToolTipText("");
        lblDienNuoc3.setIconTextGap(10);
        lblDienNuoc3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDienNuoc3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDienNuoc3MouseEntered(evt);
            }
        });
        pnlNav.add(lblDienNuoc3);

        space6.setBackground(new java.awt.Color(249, 249, 249));
        space6.setForeground(new java.awt.Color(255, 255, 255));
        space6.setMaximumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout space6Layout = new javax.swing.GroupLayout(space6);
        space6.setLayout(space6Layout);
        space6Layout.setHorizontalGroup(
            space6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        space6Layout.setVerticalGroup(
            space6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlNav.add(space6);

        lblPhong.setForeground(new java.awt.Color(51, 51, 51));
        lblPhong.setText("item 3");
        lblPhong.setToolTipText("");
        lblPhong.setIconTextGap(10);
        lblPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPhongMouseEntered(evt);
            }
        });
        pnlNav.add(lblPhong);

        space7.setBackground(new java.awt.Color(249, 249, 249));
        space7.setForeground(new java.awt.Color(255, 255, 255));
        space7.setMaximumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout space7Layout = new javax.swing.GroupLayout(space7);
        space7.setLayout(space7Layout);
        space7Layout.setHorizontalGroup(
            space7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        space7Layout.setVerticalGroup(
            space7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlNav.add(space7);

        lblHoaDon.setForeground(new java.awt.Color(51, 51, 51));
        lblHoaDon.setText("item 3");
        lblHoaDon.setToolTipText("");
        lblHoaDon.setIconTextGap(10);
        lblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHoaDonMouseEntered(evt);
            }
        });
        pnlNav.add(lblHoaDon);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pnlNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNav, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        setBounds(0, 0, 674, 423);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlNavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNavMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_pnlNavMouseEntered

    private void pnlNavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNavMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_pnlNavMouseExited

    private void lblSideBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSideBarMouseClicked

        if (navOpen == false) {
            lblNguoiThue.setToolTipText(null);
            lblSideBar.setToolTipText(null);
            lblDoanhThu.setToolTipText(null);
            lblChiNhanh.setToolTipText(null);
            lblPhong.setToolTipText(null);
            lblHopDong.setToolTipText(null);
            lblDienNuoc3.setToolTipText(null);
            lblHoaDon.setToolTipText(null);
            expandSidebar();
            navOpen = true;
        } else {
            lblNguoiThue.setToolTipText("Người thuê");
            lblSideBar.setToolTipText("Thanh bên");
            lblDoanhThu.setToolTipText("Doanh thu");
            lblChiNhanh.setToolTipText("Chi nhánh");
            lblPhong.setToolTipText("Phòng");
            lblHopDong.setToolTipText("Hợp đồng");
            lblDienNuoc3.setToolTipText("Điện nước");
            lblHoaDon.setToolTipText("Hóa đơn");
            collapseSidebar();
            navOpen = false;
        }
    }//GEN-LAST:event_lblSideBarMouseClicked

    private void lblSideBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSideBarMouseEntered
        // TODO add your handling code here:
        HoverUtil.setHoverEffect(lblSideBar);
    }//GEN-LAST:event_lblSideBarMouseEntered

    private void lblSideBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSideBarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSideBarMouseExited

    private void lblNguoiThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNguoiThueMouseClicked
        // TODO add your handling code here:
        this.cardLayout.show(this.mainPanel, Constrants.NGUOITHUE_PANEL);
    }//GEN-LAST:event_lblNguoiThueMouseClicked

    private void lblNguoiThueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNguoiThueMouseEntered
        // TODO add your handling code here:
        HoverUtil.setHoverEffect(lblNguoiThue);
    }//GEN-LAST:event_lblNguoiThueMouseEntered

    private void lblNguoiThueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNguoiThueMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_lblNguoiThueMouseExited

    private void lblDoanhThuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuMouseEntered
        // TODO add your handling code here:
        HoverUtil.setHoverEffect(lblDoanhThu);
    }//GEN-LAST:event_lblDoanhThuMouseEntered

    private void lblHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoaDonMouseEntered
        // TODO add your handling code here:
        HoverUtil.setHoverEffect(lblHoaDon);
    }//GEN-LAST:event_lblHoaDonMouseEntered

    private void lblPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhongMouseEntered
        // TODO add your handling code here:
        HoverUtil.setHoverEffect(lblPhong);
    }//GEN-LAST:event_lblPhongMouseEntered

    private void lblDienNuoc3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDienNuoc3MouseEntered
        // TODO add your handling code here:
        HoverUtil.setHoverEffect(lblDienNuoc3);
    }//GEN-LAST:event_lblDienNuoc3MouseEntered

    private void lblChiNhanhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChiNhanhMouseEntered
        // TODO add your handling code here:
        HoverUtil.setHoverEffect(lblChiNhanh);
    }//GEN-LAST:event_lblChiNhanhMouseEntered

    private void lblHopDongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHopDongMouseEntered
        // TODO add your handling code here:
        HoverUtil.setHoverEffect(lblHopDong);
    }//GEN-LAST:event_lblHopDongMouseEntered

    private void lblDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuMouseClicked
        // TODO add your handling code here:
        this.cardLayout.show(this.mainPanel, Constrants.DOANHTHU_PANEL);
    }//GEN-LAST:event_lblDoanhThuMouseClicked

    private void lblHopDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHopDongMouseClicked
        // TODO add your handling code here:
        this.cardLayout.show(this.mainPanel, Constrants.HOPDONG_PANEL);
    }//GEN-LAST:event_lblHopDongMouseClicked

    private void lblChiNhanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChiNhanhMouseClicked
        // TODO add your handling code here:
        this.cardLayout.show(this.mainPanel, Constrants.CHINHANH_PANEL);
    }//GEN-LAST:event_lblChiNhanhMouseClicked

    private void lblDienNuoc3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDienNuoc3MouseClicked
        // TODO add your handling code here:
        this.cardLayout.show(this.mainPanel, Constrants.DIENNUOC_PANEL);
    }//GEN-LAST:event_lblDienNuoc3MouseClicked

    private void lblPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhongMouseClicked
        // TODO add your handling code here:
        this.cardLayout.show(this.mainPanel, Constrants.PHONG_PANEL);
    }//GEN-LAST:event_lblPhongMouseClicked

    private void lblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoaDonMouseClicked
        // TODO add your handling code here:
        this.cardLayout.show(this.mainPanel, Constrants.HOADON_PANEL);
    }//GEN-LAST:event_lblHoaDonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    private void expandSidebar() {
        if (collapseTimer != null && collapseTimer.isRunning()) {
            collapseTimer.stop();
        }
        expandTimer = new Timer(ANIMATION_DELAY, (ActionEvent e) -> {
            int currentWidth = pnlNav.getWidth();
            if (currentWidth < EXPANDED_WIDTH) {
                pnlNav.setPreferredSize(new Dimension(currentWidth + STEP_SIZE, pnlNav.getHeight()));
                pnlNav.revalidate();
            } else {
                ((Timer) e.getSource()).stop();
                // Hiện chữ khi đủ rộng
                lblSideBar.setText("");
                lblNguoiThue.setText("Người thuê");
                lblDoanhThu.setText("Doanh thu");
                lblChiNhanh.setText("Chi chánh");
                lblPhong.setText("Phòng");
                lblHopDong.setText("Hợp đồng");
                lblHoaDon.setText("Hóa đơn");
                lblDienNuoc3.setText("Điện nước");

            }
        });
        expandTimer.start();
    }

    private void collapseSidebar() {
        if (expandTimer != null && expandTimer.isRunning()) {
            expandTimer.stop();
        }
        collapseTimer = new Timer(ANIMATION_DELAY, (ActionEvent e) -> {
            int currentWidth = pnlNav.getWidth();
            if (currentWidth > COLLAPSED_WIDTH) {
                pnlNav.setPreferredSize(new Dimension(currentWidth - STEP_SIZE, pnlNav.getHeight()));
                pnlNav.revalidate();
            } else {
                ((Timer) e.getSource()).stop();
                lblSideBar.setText("");
                lblNguoiThue.setText("");
                lblDoanhThu.setText("");
                lblChiNhanh.setText("");
                lblPhong.setText("");
                lblHopDong.setText("");
                lblHoaDon.setText("");
                lblDienNuoc3.setText("");
            }
        });
        collapseTimer.start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblChiNhanh;
    private javax.swing.JLabel lblDienNuoc3;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblHopDong;
    private javax.swing.JLabel lblNguoiThue;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblSideBar;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnlNav;
    private javax.swing.JPanel space1;
    private javax.swing.JPanel space2;
    private javax.swing.JPanel space3;
    private javax.swing.JPanel space4;
    private javax.swing.JPanel space5;
    private javax.swing.JPanel space6;
    private javax.swing.JPanel space7;
    // End of variables declaration//GEN-END:variables
    private CardLayout cardLayout = new CardLayout();

    private void initPanel() {
        this.mainPanel.setLayout(this.cardLayout);

        HomePanel homePanel = new HomePanel();
        NguoiThuePanel NguoithuePanel = new NguoiThuePanel();
        ChiNhanhPanel chiNhanhPanel = new ChiNhanhPanel();
        DienNuocPanel dienNuocPanel = new DienNuocPanel();
        DoanhthuPanel doanhthuPanel = new DoanhthuPanel();
        HoaDonPanel hoaDonPanel = new HoaDonPanel();
        HopDongPanel hopDongPanel = new HopDongPanel();
        PhongPanel phongPanel = new PhongPanel();
        
        this.mainPanel.add(Constrants.HOME_PANEL, homePanel);
        this.mainPanel.add(Constrants.NGUOITHUE_PANEL, NguoithuePanel);
        this.mainPanel.add(Constrants.CHINHANH_PANEL, chiNhanhPanel);
        this.mainPanel.add(Constrants.DIENNUOC_PANEL, dienNuocPanel);
        this.mainPanel.add(Constrants.DOANHTHU_PANEL, doanhthuPanel);
        this.mainPanel.add(Constrants.HOADON_PANEL, hoaDonPanel);
        this.mainPanel.add(Constrants.HOPDONG_PANEL, hopDongPanel);
        this.mainPanel.add(Constrants.PHONG_PANEL, phongPanel);
        
         this.cardLayout.show(this.mainPanel, Constrants.HOME_PANEL);
        
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

}
