package poly.cafe.ui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Phu Pham
 */
public class NguoiThuePanel extends javax.swing.JPanel {
private String selectedId = null;
    /**
     * Creates new form NguoiThuePanel
     */
    public NguoiThuePanel() {
        initComponents();
        loadNguoiThueToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtHoTen = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        txtCmndCccd = new javax.swing.JTextField();
        txtCreate = new javax.swing.JButton();
        txtUpdate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtHoTen.setText("jTextField1");

        txtSoDienThoai.setText("jTextField1");

        txtCCCD.setText("jTextField1");

        txtCmndCccd.setText("jTextField1");

        txtCreate.setText("jButton1");
        txtCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateActionPerformed(evt);
            }
        });

        txtUpdate.setText("Cập nhật");
        txtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCmndCccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCreate)
                                .addGap(18, 18, 18)
                                .addComponent(txtUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCmndCccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreate)
                    .addComponent(txtUpdate)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row != -1) {
            txtHoTen.setText(jTable1.getValueAt(row, 1).toString());
            txtSoDienThoai.setText(jTable1.getValueAt(row, 2).toString());
            txtCmndCccd.setText(jTable1.getValueAt(row, 3).toString());
            // Lưu lại ID để cập nhật/xóa
            selectedId = jTable1.getValueAt(row, 0).toString();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateActionPerformed
        // TODO add your handling code here:
        createNguoiThue();
    }//GEN-LAST:event_txtCreateActionPerformed

    private void txtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateActionPerformed
        // TODO add your handling code here:
        updateNguoiThue();
    }//GEN-LAST:event_txtUpdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        deleteNguoiThue();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void createNguoiThue() {
        String hoTen = txtHoTen.getText();
        String soDienThoai = txtSoDienThoai.getText();
        String cmndCccd = txtCmndCccd.getText();
        poly.cafe.dao.NguoiThueDAO nguoiThueDAO = new poly.cafe.dao.impl.NguoiThueDAOImpl();
        poly.cafe.entity.NguoiThue nguoiThue = poly.cafe.entity.NguoiThue.builder()
            .hoTen(hoTen)
            .soDienThoai(soDienThoai)
            .cmndCccd(cmndCccd)
            .build();
        nguoiThueDAO.insert(nguoiThue);
        loadNguoiThueToTable();
    }

    private void loadNguoiThueToTable() {
        poly.cafe.dao.NguoiThueDAO nguoiThueDAO = new poly.cafe.dao.impl.NguoiThueDAOImpl();
        java.util.List<poly.cafe.entity.NguoiThue> danhSach = nguoiThueDAO.findAll();
        String[] columnNames = {"ID", "Họ tên", "SĐT", "CMND/CCCD"};
        Object[][] data = new Object[danhSach.size()][4];
        for (int i = 0; i < danhSach.size(); i++) {
            poly.cafe.entity.NguoiThue nt = danhSach.get(i);
            data[i][0] = nt.getMaNguoiThue();
            data[i][1] = nt.getHoTen();
            data[i][2] = nt.getSoDienThoai();
            data[i][3] = nt.getCmndCccd();
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
    }

    private void updateNguoiThue() {
        if (selectedId == null) return;
        poly.cafe.dao.NguoiThueDAO nguoiThueDAO = new poly.cafe.dao.impl.NguoiThueDAOImpl();
        poly.cafe.entity.NguoiThue nguoiThue = poly.cafe.entity.NguoiThue.builder()
            .maNguoiThue(java.util.UUID.fromString(selectedId))
            .hoTen(txtHoTen.getText())
            .soDienThoai(txtSoDienThoai.getText())
            .cmndCccd(txtCmndCccd.getText())
            .build();
        nguoiThueDAO.update(nguoiThue);
        loadNguoiThueToTable();
    }

    private void deleteNguoiThue() {
        if (selectedId == null) return;
        poly.cafe.dao.NguoiThueDAO nguoiThueDAO = new poly.cafe.dao.impl.NguoiThueDAOImpl();
        nguoiThueDAO.delete(java.util.UUID.fromString(selectedId));
        loadNguoiThueToTable();
        // Xóa input
        txtHoTen.setText("");
        txtSoDienThoai.setText("");
        txtCmndCccd.setText("");
        selectedId = null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtCmndCccd;
    private javax.swing.JButton txtCreate;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JButton txtUpdate;
    // End of variables declaration//GEN-END:variables
}
